# Generated by Django 6.1.1 on 2026-09-04 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseUML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('posicion_x', models.FloatField(default=0.0)),
                ('posicion_y', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='AtributoUML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_dato', models.CharField(max_length=50)),
                ('visibilidad', models.CharField(choices=[('Public', 'Public (+)'), ('Private', 'Private (-)'), ('Protected', 'Protected (#)')], default='Private', max_length=20)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='diagramas.claseuml')),
            ],
        ),
        migrations.CreateModel(
            name='Diagrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagramas', to='proyectos.proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='claseuml',
            name='diagrama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='diagramas.diagrama'),
        ),
        migrations.CreateModel(
            name='RelacionUML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Asociacion', 'Asociación'), ('Herencia', 'Herencia'), ('Composicion', 'Composición'), ('Agregacion', 'Agregación'), ('Dependencia', 'Dependencia')], max_length=50)),
                ('multiplicidad_origen', models.CharField(blank=True, max_length=10, null=True)),
                ('multiplicidad_destino', models.CharField(blank=True, max_length=10, null=True)),
                ('clase_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_entrantes', to='diagramas.claseuml')),
                ('clase_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_salientes', to='diagramas.claseuml')),
                ('diagrama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones', to='diagramas.diagrama')),
            ],
        ),
        migrations.CreateModel(
            name='VersionDiagrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_snapshot', models.JSONField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('diagrama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='diagramas.diagrama')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
