# Generated by Django 6.1.1 on 2026-09-23 16:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagramas', '0005_remove_legacy_presence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diagrama',
            name='revision',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PlanIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('operaciones', models.JSONField()),
                ('revision_base', models.PositiveBigIntegerField()),
                ('request_hash', models.CharField(max_length=64)),
                ('expira_en', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('applied', 'Aplicado'), ('expired', 'Expirado')], default='pending', max_length=12)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=128)),
                ('resultado', models.JSONField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aplicacion', models.DateTimeField(blank=True, null=True)),
                ('diagrama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_ia', to='diagramas.diagrama')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['diagrama', 'usuario', 'estado'], name='diagramas_p_diagram_b82a76_idx')],
            },
        ),
    ]
